name: Multi Environment Deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'multilevel-deploy'
        required: true
        default: 'dev'
        type: choice
        options:
        - dev
        - staging
        - prod


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: deploy
        run: |
          echo "Deploying to environment: ${{ github.event.inputs.environment  }}"
